# ================= IP address =================
PUBLIC_IP_ADDR=${PUBLIC_IP_ADDR}

# ================= PostgreSQL =================
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_DATABASE=${POSTGRES_DATABASE}

# ================= TLS configuration =================
FULL_DOMAIN=${FULL_DOMAIN}
CERT_PATH=${CERT_PATH}
TLS_ENABLED=${TLS_ENABLED}

# ================= TURN =================
TURN_RANDOM_SECRET=${TURN_RANDOM_SECRET}
TURN_MIN_PORT=${TURN_MIN_PORT}
TURN_MAX_PORT=${TURN_MAX_PORT}

# ================= PGAdmin =================
PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

# ================= Grafana =================
GRAFANA_USER=${GRAFANA_USER}
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}